"""empty message

Revision ID: 4b575885fda6
Revises: eacb344238c7
Create Date: 2019-10-01 14:00:07.298068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b575885fda6'
down_revision = 'eacb344238c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_name', sa.String(length=50), nullable=True),
    sa.Column('recipe_link', sa.String(length=150), nullable=True),
    sa.Column('recipe_state', sa.Enum('active', 'archive', 'new', name='recipestate'), nullable=True),
    sa.Column('recipe_notes', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('recipe_id')
    )
    op.add_column('ingredients', sa.Column('recipe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingredients', 'recipes', ['recipe_id'], ['recipe_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'recipe_id')
    op.drop_table('recipes')
    # ### end Alembic commands ###
