"""empty message

Revision ID: eacb344238c7
Revises: 
Create Date: 2019-09-30 18:04:10.238392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacb344238c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(), nullable=True),
    sa.Column('ingredient_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ingredient_id')
    )
    op.create_table('unit_of_measure',
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('measure_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('measure_id')
    )
    op.create_table('ingredients',
    sa.Column('ingredients_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('measure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.ingredient_id'], ),
    sa.ForeignKeyConstraint(['measure_id'], ['unit_of_measure.measure_id'], ),
    sa.PrimaryKeyConstraint('ingredients_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingredients')
    op.drop_table('unit_of_measure')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
